---
- hosts: localhost
  vars:
    # Все что нам надо на входе плейбука
    # Если какие-то переменные не определены, то будут браться из ролей в defaults

    g_rancher_new_local_admin_password: "secret"

    g_openldap_rancher_admin_username: "root"
    g_openldap_rancher_admin_password: "wheel"

    g_openldap_other_users_usernames: "user01,user02,user03,user04"
    g_openldap_other_users_passwords: "pwd01,pwd02,pwd03,pwd04"

    g_openldap_server_port: 1389
    g_openldap_root: "dc=windowsmustdie,dc=org"

    # openldap_docker_image: "bitnami/openldap:2.4"
    rancher_docker_image: "rancher/rancher:stable"

  tasks:
    - name: Check os type. Working with RedHat, CentOS, Ubuntu
      fail:
        msg: "Host OS is not suitable for this playbook."
      when: ansible_os_family != 'CentOS' and ansible_os_family != 'RedHat' and ansible_os_family != 'Rocky' and ansible_distribution != 'Ubuntu'

    - name: Start/check docker service
      service:
        name: docker
        state: started

    - name: Install/check Docker Module for Python
      pip:
        name: docker

    - name: Run OpenLDAP
      include_role:
        name: run_openldap

    - name: Run Rancher
      include_role:
        name: run_rancher
