---
- name: Set Rancher variables
  set_fact:
    rancher_new_password: g_rancher_new_local_admin_password
  when: g_rancher_new_local_admin_password is defined

- include_tasks: rancher_start_container.yml
- include_tasks: rancher_configuring.yml
